version: '3'

services:

  # Service Consul
  consul:
    image: consul:1.15.4
    container_name: consul-container
    ports:
      - "8500:8500" 
    networks:
      - microservices-network

  # Service Gateway
  gateway-service:
    build:
      context: ./gateway
    ports:
      - "5000:5000"
    depends_on:
      - consul
    networks:
      - microservices-network
    environment:
      SPRING_CLOUD_CONSUL_HOST: consul
      SPRING_CLOUD_CONSUL_PORT: 8500
      SPRING_CLOUD_CONSUL_DISCOVERY_ENABLED: 'true'

  # Service Client
  client-service:
    build:
      context: ./client
    ports:
      - "5002:5002"
    depends_on:
      - consul
      - gateway-service
    networks:
      - microservices-network
    environment:
      SPRING_CLOUD_CONSUL_HOST: consul
      SPRING_CLOUD_CONSUL_PORT: 8500
      SPRING_CLOUD_CONSUL_DISCOVERY_ENABLED: 'true'
  # Service Voiture
  voiture-service:
    build:
      context: ./car
    ports:
      - "5001:5001"
    depends_on:
      - consul
      - gateway-service
    networks:
      - microservices-network
    environment:
      SPRING_CLOUD_CONSUL_HOST: consul
      SPRING_CLOUD_CONSUL_PORT: 8500
      SPRING_CLOUD_CONSUL_DISCOVERY_ENABLED: 'true'

networks:
  microservices-network:
    driver: bridge
