server:
  port: 5001

spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery: car-service
  application:
    name: car-service
  h2:
    console:
      enabled: true
      path: /h2
    datasource:
      url: jdbc:h2:mem:mydb2
      username: sa
      password:
      driverClassName: org.h2.Driver
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
